nats:
  image: nats:2.3.4  # specify the NATS image version that supports JetStream
  cluster:
    enabled: true
    replicas: 3  # specify the number of nodes in the cluster
  jetstream:
    enabled: true
    memStorage:
      enabled: true
      size: 2Gi
    fileStorage:
      enabled: true
      size: 10Gi
      storageClassName: standard
