apiVersion: v1
kind: Service
metadata:
  name: nats-headless
spec:
  clusterIP: None  # This makes the service headless
  ports:
    - name: client
      port: 4222
      targetPort: 4222
    - name: cluster
      port: 6222
      targetPort: 6222
    - name: monitor
      port: 8222
      targetPort: 8222
  selector:
    app.kubernetes.io/name: nats

---
nats:
  image: nats:2.3.4  # Use the NATS image version that supports TLS and JetStream
  jetstream:
    enabled: true
  cluster:
    enabled: true
    replicas: 3  # Specify the number of nodes in the cluster
    tls:
      # Enable TLS for client connections and route connections
      enabled: true  
      # Name of the Kubernetes secret holding the TLS certs
      secret:
        name: nats-tls  
  leafnodes:
    enabled: false
  externalAccess: true  # Enables external access
  service:
    name: nats-headless  # Use the headless service for clustering

---
apiVersion: v1
kind: Secret
metadata:
  name: nats-tls
type: Opaque
data:
  # Your base64-encoded TLS certificates and keys
  ca.crt: |
    <base64-encoded-ca-cert>
  tls.crt: |
    <base64-encoded-tls-cert>
  tls.key: |
    <base64-encoded-tls-key>
  route-tls.crt: |
    <base64-encoded-route-tls-cert>
  route-tls.key: |
    <base64-encoded-route-tls-key>
